import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastProvider } from "@/components/ToastProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <nav className="flex justify-between items-center p-4 bg-gray-100 dark:bg-gray-900">
            <div className="font-bold text-lg">EV Charger Manager</div>
            <div className="flex gap-4">
              <Link href="/">Home</Link>
              <Link href="/auth">Sign In / Sign Up</Link>
            </div>
          </nav>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
